---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no

   tasks:
   - name: Update the machine
     tags: upd
     yum:
       update_only: yes


   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - nano
         - net-tools
         - tcpdump
         - nmap
         - wireshark
         - git
         - wget
         - iproute
         - psmisc
         - yum-utils
         - chrony
         - telnet
         - iptables-services
         - gcc
         - scl-utils
         - centos-release-scl
         state: present

   - name: install several packages after deleting iptables
     tags: iptables
     yum: 
       name: 
         - iptables
         - iproute
         - dhclient
         - plymouth
         - initscripts
         - kbd
         - kexec-tools
         - dracut
         - firewalld
         - iptables-services
         - mlocate
       state: present


   - name: configure NTP
     tags: NTP
     shell: |
       updatedb      
       timedatectl set-ntp true
       timedatectl set-timezone Europe/Berlin



   - name: Install essential Packages to run "thc-ipv6" repo Toolkit
     tags: thc-essentials
     yum: 
       name: 
         - libpcap-devel
         - openssl-devel
         - libnetfilter_queue-devel
         - gcc
       state: present


   - name: Clone thc-ipv6 github repository
     tags: repo
     git:
       repo: https://github.com/vanhauser-thc/thc-ipv6.git
       dest: /root/hacker-tool
       clone: yes
       update: yes


   - name: Play around withing the repo 
     tags: in-repo
     shell: make all && make install
     args:
       chdir: /root/hacker-tool

   - name: Create attack script 
     tags: attack
     ansible.builtin.template:
       src: /root/DS-Lite_Test_Bed/files/attack.txt
       dest: /root/attack.sh
       owner: root
       mode: '755'


   - name: install several essential packages for thc-hydra
     tags: hydra
     yum: 
       name: 
         - dnf
         - libssh-devel
         - pcre-devel
         - gtk2-devel
         - mariadb-devel
         - postgresql-devel
         - libsvm-devel
         - libgcrypt-devel
         - desktop-file-utils
       state: present
   
   - name: Clone "thc-hydra" github repository
     tags: hydra
     git:
       repo: https://github.com/vanhauser-thc/thc-hydra
       dest: /root/hydra
       clone: yes
       update: yes

   - name: Play around withing the repo 
     tags: hydra
     shell: |
       dnf --enablerepo=powertools install libidn-devel -y
       ./configure
       make
       make install
     args:
       chdir: /root/hydra


   - name: Create hydra attack script 
     tags: attack-2
     ansible.builtin.template:
       src: /root/DS-Lite_Test_Bed/files/attack-2.txt
       dest: /root/attack-2.sh
       owner: root
       mode: '755'

   - name: Clone "dns64perf" github repository
     tags: dns64
     shell: git clone -b feature/multiport https://github.com/bakaid/dns64perfpp.git
     args:
       chdir: /root/
    
   - name: install several essential packages for dns64
     tags: dns64
     yum: 
       name: 
         - centos-release-scl
         - llvm-toolset-7
       state: present

# in case of erros while running the last module: -

# make
# make -std=c++1y -pedantic
# make install
# make install -std=c++1y -pedantic



   - name: Play around within the repo 
     tags: dns64
     shell: |
       scl enable llvm-toolset-7 bash
       make
       sleep 5 # wait till make stuff is finished
       make install
     args:
       chdir: /root/dns64perfpp

   - name: Create dns64perf++ attacking script 
     tags: dns64
     ansible.builtin.template:
       src: /root/DS-Lite_Test_Bed/files/attack-3.txt
       dest: /root/attack-3.sh
       owner: root
       mode: '755'

