---
-  hosts: localhost
   any_errors_fatal: true
   gather_facts: no

   tasks:
   - name: Update the machine
     tags: upd
     yum:
       update_only: yes


   - name: Install General Essential packages
     tags: essentials
     yum: 
       name: 
         - nano
         - net-tools
         - tcpdump
         - nmap
         - wireshark
         - git
         - wget
         - iproute
         - psmisc
         - yum-utils
         - chrony
         - telnet
         - iptables-services
       state: present

   - name: install several packages in case of deleting iptables
     tags: iptables
     yum: 
       name: 
         - iptables
         - iproute
         - dhclient
         - plymouth
         - initscripts
         - kbd
         - kexec-tools
         - dracut
         - firewalld
         - iptables-services
         - mlocate
       state: present


   - name: Set the Timezone.
     tags: NTP
     shell: |
       timedatectl set-ntp true
       timedatectl set-timezone Europe/Berlin


   - name: Edit "/etc/sysctl.conf" file
     tags: sysctl
     lineinfile:
       path: /etc/sysctl.conf
       line: " net.ipv4.ip_forward = 1 \n  net.ipv6.conf.all.forwarding = 1 \n net.ipv4.conf.all.accept_redirects = 0  \n net.ipv4.conf.all.send_redirects = 0 "  


   - name: Create iproute file 
     tags: routing
     ansible.builtin.template:
       src: /root/DS-Lite_Test_Bed/files/IPv4-client-networking.txt
       dest: /root/networking.sh
       owner: root
       mode: '755'


   - name: Run networking.sh
     tags: routing
     shell: |
       cd 
       ./networking.sh




   - name: Solve an issue of "too many open files" part 1 insert line "/etc/security/limits.conf"
     tags: files
     lineinfile:
       path: /etc/security/limits.conf
       regexp: '^#<domain>        <type>  <item>  <value>'
       line: '<domain>        <type>  <item>  <value> \n root         hard    nofile  1000000'


   - name: Solve an issue of "too many open files" part 2
     tags: files
     shell: |
       ulimit -n 65536 



   - name: Create auto-script to automate dns64perf++ Attack
     tags: script
     ansible.builtin.template:
       src: /root/DS-Lite_Test_Bed/files/auto-attack.txt
       dest: /root/auto-attack.sh
       owner: root
       mode: '755'

